% =========================================================================
% FILE: icn_cache_simulator.m
% DESCRIPTION: Main execution script for 6G-ICN traditional caching benchmark.
% =========================================================================
clear; clc; close all;

%% 1. Simulation Parameters
num_requests = 5000;       % Total content requests generated by 6G UEs
catalog_size = 1000;       % Total unique content pieces available in network
zipf_alpha = 0.8;          % Content popularity skewness factor (Zipf distribution)
cache_capacities = [10, 20, 50, 100, 150, 200]; % Test multiple cache sizes

% Network Latency Matrix (in milliseconds)
latency_local_cache = 1;   % Edge Node Hit
latency_publisher   = 50;  % Cache Miss -> Fetching from remote publisher

%% 2. Generate Content Request Stream (Zipf Distribution)
fprintf('Generating Zipf-distributed content requests...\n');
ranks = 1:catalog_size;
pmf = (1./(ranks.^zipf_alpha)) / sum(1./(ranks.^zipf_alpha));
cdf = cumsum(pmf);

% Map request sequence
request_stream = zeros(1, num_requests);
for i = 1:num_requests
    r = rand();
    request_stream(i) = find(cdf >= r, 1, 'first');
end

%% 3. Run Performance Evaluation Loop
algorithms = {'LRU', 'LFU', 'FIFO', 'Random'};
hit_ratios = zeros(length(algorithms), length(cache_capacities));
avg_latencies = zeros(length(algorithms), length(cache_capacities));

for c_idx = 1:length(cache_capacities)
    capacity = cache_capacities(c_idx);
    fprintf('Simulating Cache Capacity: %d items...\n', capacity);
    
    for a_idx = 1:length(algorithms)
        algo = algorithms{a_idx};
        
        % Initialize ICN Edge Node Cache Engine
        cache_engine = IcnCacheEngine(capacity, algo);
        
        total_hits = 0;
        total_latency = 0;
        
        % Processing the Interest Packet Stream
        for req = request_stream
            % Step A: Lookup Content via ICN Engine
            is_hit = cache_engine.check_and_update(req);
            
            % Step B: Record Metrics
            if is_hit
                total_hits = total_hits + 1;
                total_latency = total_latency + latency_local_cache;
            else
                total_latency = total_latency + latency_publisher;
            end
        end
        
        % Store computed metrics
        hit_ratios(a_idx, c_idx) = (total_hits / num_requests) * 100;
        avg_latencies(a_idx, c_idx) = total_latency / num_requests;
    end
end

%% 4. Graphical Comparative Analysis Visualization
figure('Position', [100, 100, 1100, 450]);

% Plot 1: Cache Hit Ratio Comparative Performance
subplot(1, 2, 1);
hold on;
markers = {'o-', 's-', 'd-', '^-'};
for a_idx = 1:length(algorithms)
    plot(cache_capacities, hit_ratios(a_idx, :), markers{a_idx}, 'LineWidth', 1.8);
end
grid on;
xlabel('Edge Cache Capacity (Items)');
ylabel('Cache Hit Ratio (%)');
title('ICN Framework: Cache Hit Ratio Comparison');
legend(algorithms, 'Location', 'best');

% Plot 2: Average E2E Latency Profile
subplot(1, 2, 2);
hold on;
for a_idx = 1:length(algorithms)
    plot(cache_capacities, avg_latencies(a_idx, :), markers{a_idx}, 'LineWidth', 1.8);
end
grid on;
xlabel('Edge Cache Capacity (Items)');
ylabel('Avg E2E Request Latency (ms)');
title('ICN Framework: Average Delivery Latency');
legend(algorithms, 'Location', 'best');

fprintf('\nSimulation Completed Successfully.\n');

% =========================================================================
% MAKE SURE THIS EXACT BLOCK IS AT THE VERY END OF icn_cache_simulator.m
% =========================================================================
fprintf('\nSimulation Completed Successfully. Saving workspace...\n');

% Save all calculated matrices to the file
save('simulation_results.mat', 'cache_capacities', 'algorithms', 'hit_ratios', 'avg_latencies');

fprintf('Data successfully stored in simulation_results.mat\n');
